/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package csapat3.krutillazs.beadando.Windows;

import csapat3.krutillazs.beadando.Enums.LocalizationList;
import csapat3.krutillazs.beadando.Enums.LogType;
import csapat3.krutillazs.beadando.Localization.Localization;
import csapat3.krutillazs.beadando.Utils.Logger;
import csapat3.krutillazs.beadando.Utils.Window;

import javax.swing.*;

/**
 *
 * @author flawl
 */
public class LanguageSelect extends javax.swing.JPanel {

    public static void main(String[] args) {
        JFrame frame = new JFrame("LanguageSelect");
        frame.setContentPane(new LanguageSelect());
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
        frame.setResizable(false);
        frame.setLocationRelativeTo(null);
    }

    /**
     * Creates new form LanguageSelect
     */
    public LanguageSelect() {
        Logger.log("Opening Language Select form", LogType.INFO);
        initComponents();
                Logger.log("Opened Language Select form", LogType.INFO);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtInfoText = new javax.swing.JLabel();
        bttnHU = new javax.swing.JButton();
        bttnEN = new javax.swing.JButton();

        txtInfoText.setText("Please choose language / Kérlek válassz nyelvet.");

        bttnHU.setText("Magyar");
        bttnHU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnHUActionPerformed(evt);
            }
        });

        bttnEN.setText("English");
        bttnEN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnENActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bttnHU)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bttnEN))
                    .addComponent(txtInfoText))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(txtInfoText)
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttnHU)
                    .addComponent(bttnEN))
                .addContainerGap(78, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bttnHUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnHUActionPerformed
        Logger.log("Selected HU language, loading", LogType.INFO);
        Localization localization = Localization.getInstance();
        localization.setLocalization(LocalizationList.HU);

        LoginWindow loginWindow = new LoginWindow();
        loginWindow.setLocationRelativeTo(null);
        loginWindow.setVisible(true);

        Window.close(this);
    }//GEN-LAST:event_bttnHUActionPerformed

    private void bttnENActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnENActionPerformed
        Logger.log("Selected EN language, loading", LogType.INFO);
        Localization localization = Localization.getInstance();
        localization.setLocalization(LocalizationList.EN);

        LoginWindow loginWindow = new LoginWindow();
        loginWindow.setLocationRelativeTo(null);
        loginWindow.setVisible(true);
        
        Window.close(this);
    }//GEN-LAST:event_bttnENActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnEN;
    private javax.swing.JButton bttnHU;
    private javax.swing.JLabel txtInfoText;
    // End of variables declaration//GEN-END:variables
}
