/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package csapat3.krutillazs.beadando.Windows;

import csapat3.krutillazs.beadando.Models.Session;
import csapat3.krutillazs.beadando.Modules.DatabaseManager;
import java.sql.SQLException;
import javax.swing.*;

import csapat3.krutillazs.beadando.ResourceBundle.ResourceBundleLocalization;
import csapat3.krutillazs.beadando.Services.GeneralService;
import csapat3.krutillazs.beadando.Interfaces.IContainer;

public class LoginWindow extends javax.swing.JFrame {
    private final IContainer container;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane txtPnlUserName;
    private javax.swing.JPasswordField txtPsswrdFldPassword;
    // End of variables declaration//GEN-END:variables

    /**
     * Creates new form LoginWindow
     */
    public LoginWindow() {
        initComponents();
        container = IContainer.getInstance();
        container.resolve(DatabaseManager.class).createConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPnlUserName = new javax.swing.JTextPane();
        txtPsswrdFldPassword = new javax.swing.JPasswordField();
        bttnLogin = new javax.swing.JButton();

        ResourceBundleLocalization resourceBundleLocalization = ResourceBundleLocalization.getInstance();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(resourceBundleLocalization.get("login_title"));
        setBackground(new java.awt.Color(255, 255, 255));
        setName("frmLogin"); // NOI18N
        setResizable(false);

        jLabel1.setText(resourceBundleLocalization.get("username"));

        jLabel2.setText(resourceBundleLocalization.get("password"));

        jScrollPane1.setViewportView(txtPnlUserName);

        bttnLogin.setText(resourceBundleLocalization.get("login"));
        bttnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bttnLoginMouseClicked(evt);
            }
        });
        bttnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bttnLogin)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(txtPsswrdFldPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))))
                .addContainerGap(249, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPsswrdFldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(bttnLogin)
                .addGap(31, 31, 31))
        );

        bttnLogin.getAccessibleContext().setAccessibleName("bttnLogin");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttnLoginMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bttnLoginMouseClicked

    private void bttnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnLoginActionPerformed
        try {
            String password = new String(txtPsswrdFldPassword.getPassword());
            String encryptedPassword = container.resolve(GeneralService.class).encryptPassword(password);

            if (! container.resolve(DatabaseManager.class).verifyUserLogin(txtPnlUserName.getText(), encryptedPassword)) {
                JOptionPane.showMessageDialog(null, "Sikertelen bejelentkezés. Ellenőrízd a felhasználóneved és jelszavad!", "Hitelesítés", JOptionPane.ERROR_MESSAGE);
                Session.currentUser = container.resolve(DatabaseManager.class).getUserInformations(txtPnlUserName.getText());

                return;
            }

            JOptionPane.showMessageDialog(null,  "Sikeres belépés","Hitelesítés",JOptionPane.ERROR_MESSAGE);

        } catch(SQLException ex) {
            JOptionPane.showMessageDialog(null,  String.format("Hiba történt a hitelesítés során:\n\n%s", ex.getMessage()),"Hitelesítés",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bttnLoginActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException |
                 UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(csapat3.krutillazs.beadando.Windows.LoginWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new csapat3.krutillazs.beadando.Windows.LoginWindow().setVisible(true));
    }
}
