/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package csapat3.krutillazs.beadando.Windows;

import csapat3.krutillazs.beadando.Models.Session;
import csapat3.krutillazs.beadando.Modules.DatabaseManager;
import java.sql.SQLException;
import javax.swing.*;

import csapat3.krutillazs.beadando.Services.GeneralService;
import csapat3.krutillazs.beadando.Utils.Container;

public class LoginWindow extends javax.swing.JFrame {

    private javax.swing.JTextPane txtPnlUserName;
    private javax.swing.JPasswordField txtPsswrdFldPassword;
    private final Container container;

    /**
     * Creates new form LoginWindow
     */
    public LoginWindow() {
        initComponents();
        container = Container.getInstance();
        container.resolve(DatabaseManager.class).createConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
        txtPnlUserName = new javax.swing.JTextPane();
        txtPsswrdFldPassword = new javax.swing.JPasswordField();
        javax.swing.JButton bttnLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bejelentkezés");
        setBackground(new java.awt.Color(255, 255, 255));
        setName("frmLogin"); // NOI18N
        setResizable(false);

        jLabel1.setText("Felhasználónév:");

        jLabel2.setText("Jelszó:");

        jScrollPane1.setViewportView(txtPnlUserName);

        bttnLogin.setText("Bejelentkezés");
        bttnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bttnLoginMouseClicked(evt);
            }
        });

        bttnLogin.addActionListener(this::bttnLoginActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(txtPsswrdFldPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(bttnLogin)))
                .addContainerGap(249, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPsswrdFldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(bttnLogin)
                .addGap(28, 28, 28))
        );

        bttnLogin.getAccessibleContext().setAccessibleName("bttnLogin");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttnLoginMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bttnLoginMouseClicked

    private void bttnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnLoginActionPerformed
        try {
            String password = new String(txtPsswrdFldPassword.getPassword());
            String encryptedPassword = container.resolve(GeneralService.class).encryptPassword(password);

            if (! container.resolve(DatabaseManager.class).verifyUserLogin(txtPnlUserName.getText(), encryptedPassword)) {
                JOptionPane.showMessageDialog(null, "Sikertelen bejelentkezés. Ellenőrízd a felhasználóneved és jelszavad!", "Hitelesítés", JOptionPane.ERROR_MESSAGE);
                Session.currentUser = container.resolve(DatabaseManager.class).getUserInformations(txtPnlUserName.getText());

                return;
            }

            JOptionPane.showMessageDialog(null,  "Sikeres belépés","Hitelesítés",JOptionPane.ERROR_MESSAGE);

        } catch(SQLException ex) {
            JOptionPane.showMessageDialog(null,  String.format("Hiba történt a hitelesítés során:\n\n%s", ex.getMessage()),"Hitelesítés",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bttnLoginActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException |
                 UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginWindow().setVisible(true));
    }
}
